### ISSUE TITLE
Build error aarch64

### ISSUE THREAD

**Issue by tramhao** [trojan-gfw/openwrt-trojan#10]
I'm building trojan for lede Phicomm N1. Got the error below for openssl1.1

make[4]: Leaving directory '/home/runner/work/Actions-OpenWrt/Actions-OpenWrt/openwrt/build_dir/target-aarch64_generic_musl/openssl1.1-1.1.1d/openssl-1.1.1d'
/home/runner/work/Actions-OpenWrt/Actions-OpenWrt/openwrt/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/lib/gcc/aarch64-openwrt-linux-musl/7.5.0/../../../../aarch64-openwrt-linux-musl/bin/ld: ca.c:(.text.do_revoke+0x498): warning: too many GOT entries for -fpic, please recompile with -fPIC
/home/runner/work/Actions-OpenWrt/Actions-OpenWrt/openwrt/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/lib/gcc/aarch64-openwrt-linux-musl/7.5.0/../../../../aarch64-openwrt-linux-musl/bin/ld: final link failed: symbol needs debug section which does not exist
collect2: error: ld returned 1 exit status
make[4]: *** [apps/openssl] Error 1
make[3]: *** [all] Error 2
make[2]: *** [/home/runner/work/Actions-OpenWrt/Actions-OpenWrt/openwrt/build_dir/target-aarch64_generic_musl/openssl1.1-1.1.1d/openssl-1.1.1d/.built] Error 2
time: package/lean/openssl1.1/compile#110.22#16.58#125.19
Makefile:174: recipe for target 'all' failed
make[1]: *** [package/lean/openssl1.1/compile] Error 2
make[3]: Leaving directory '/home/runner/work/Actions-OpenWrt/Actions-OpenWrt/openwrt/build_dir/target-aarch64_generic_musl/openssl1.1-1.1.1d/openssl-1.1.1d'
Makefile:158: recipe for target '/home/runner/work/Actions-OpenWrt/Actions-OpenWrt/openwrt/build_dir/target-aarch64_generic_musl/openssl1.1-1.1.1d/openssl-1.1.1d/.built' failed
make[2]: Leaving directory '/home/runner/work/Actions-OpenWrt/Actions-OpenWrt/openwrt/package/lean/openssl1.1'
package/Makefile:107: recipe for target 'package/lean/openssl1.1/compile' failed
make[1]: Leaving directory '/home/runner/work/Actions-OpenWrt/Actions-OpenWrt/openwrt'
make: *** [package/openssl1.1/compile] Error 2
/home/runner/work/Actions-OpenWrt/Actions-OpenWrt/openwrt/include/toplevel.mk:216: recipe for target 'package/openssl1.1/compile' failed
##[error]Process completed with exit code 2.

Any ideas?

**Comment by malikshi** [comment]
you can check there maybe fix that error. https://github.com/trojan-gfw/trojan/issues/127
