### ISSUE TITLE
Error loading shared library libboost_system.so.1.71.0: No such file or directory (needed by /usr/sbin/trojan) Started!

### ISSUE THREAD

**Issue by txdywy** [trojan-gfw/openwrt-trojan#11]
I checked the openwrt to install trojan, it had libboost_system.so.1.72.0 in /usr/lib instead of 1.71.0.

Any idea to fit it?

**Comment by wongsyrone** [comment]
Recompile your ipk or install the corresponding dependencies.

**Comment by txdywy** [comment]
Thanks!
