### ISSUE TITLE
CPU: multicore_ready is false

### ISSUE THREAD

**Issue by kousyougi** [trojan-gfw/openwrt-trojan#13]
I use Qemu to run OpenWrt 19.07.1-x86_64. (Kernel Version : 4.14.167)
And I can recognize 4 cpu cores by cpuinfo in the Openwrt.

But I saw this following notice at System Log....
 daemon.notice procd: /etc/rc.d/S95trojan: multicore_ready is false
 daemon.notice procd: /etc/rc.d/S95trojan: cpunum is 1
 daemon.err trojan[1822]: Welcome to trojan 1.14.1

Does it matter to performance?

**Comment by GreaterFire** [comment]
No. Trojan is single threaded anyway.

**Comment by wongsyrone** [comment]
https://github.com/trojan-gfw/openwrt-trojan/issues/14#issuecomment-584943666
