### ISSUE TITLE
如何设置openwrt上的参数

### ISSUE THREAD

**Issue by shake** [trojan-gfw/openwrt-trojan#15]
<img width="520" alt="快照3" src="https://user-images.githubusercontent.com/78207/75420850-e4070d80-5973-11ea-9650-c951b71ebadf.png">

trojan,已经在vps装完，一切正常，域名也申请的ssl证书。pc端，利用配置文件，已经可以顺利上网。

几个问题
1：TLS host，是填写服务器的域名吗？如果选TLS，
2：TCP快速打开，需要做什么，如果选上
3：如果我的网站，只允许https访问，那么是不是不要勾选上allowlnsecure?

**Comment by shake** [comment]
net.ipv4.tcp_fastopen=3,
tcp 快速打开，需要你的vps内核打开这个功能，默认一般已经打开。

cat /proc/sys/net/ipv4/tcp_fastopen
3
表示打开

**Comment by wongsyrone** [comment]
This GUI(LuCI) is not provided by us.
