### ISSUE TITLE
基于openwrt sdk 19.07.2编译ipk失败。不解惑。

### ISSUE THREAD

**Issue by wazzx** [trojan-gfw/openwrt-trojan#18]
2.开启ssh，更新，安装运行所需环境：
（Ubuntu 18.04 LTS）
sudo apt-get install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip
apt-get install python
3.下载sdk：
wget https://downloads.openwrt.org/releases/19.07.2/targets/apm821xx/nand/openwrt-sdk-19.07.2-apm821xx-nand_gcc-7.5.0_musl.Linux-x86_64.tar.xz
4.解压sdk：
xz -d openwrt-sdk-19.07.2-apm821xx-nand_gcc-7.5.0_musl.Linux-x86_64.tar.xz
tar vxf openwrt-sdk-19.07.2-apm821xx-nand_gcc-7.5.0_musl.Linux-x86_64.tar
5.进入openwrt-sdk目录：
cd openwrt-sdk-19.07.2-apm821xx-nand_gcc-7.5.0_musl.Linux-x86_64
6.添加 feeds（以shadowsocks-libev为例）
# git clone https://github.com/shadowsocks/openwrt-feeds.git package/feeds
  git clone https://github.com/ffftwo/openwrt-trojan.git package/feeds
7.获取Makefile（以shadowsocks-libev为例）
# git clone https://github.com/shadowsocks/openwrt-shadowsocks.git package/shadowsocks-libev
  git clone https://github.com/ffftwo/openwrt-trojan package/trojan
  make menuconfig
  make package/trojan/compile V=99
编译失败：：：
 -- Configuring incomplete, errors occurred!
See also "/home/openwrt-sdk-19.07.2-apm821xx-nand_gcc-7.5.0_musl.Linux-x86_64/build_dir/target-powerpc_464fp_musl/trojan-1.14.1/CMakeFiles/CMakeOutput.log".
Makefile:86: recipe for target '/home/openwrt-sdk-19.07.2-apm821xx-nand_gcc-7.5.0_musl.Linux-x86_64/build_dir/target-powerpc_464fp_musl/trojan-1.14.1/.configured_68b329da9893e34099c7d8ad5cb9c940' failed
make[2]: *** [/home/openwrt-sdk-19.07.2-apm821xx-nand_gcc-7.5.0_musl.Linux-x86_64/build_dir/target-powerpc_464fp_musl/trojan-1.14.1/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
make[2]: Leaving directory '/home/openwrt-sdk-19.07.2-apm821xx-nand_gcc-7.5.0_musl.Linux-x86_64/package/trojan'
time: package/trojan/compile#1.01#0.44#8.13
package/Makefile:111: recipe for target 'package/trojan/compile' failed
make[1]: *** [package/trojan/compile] Error 2
make[1]: Leaving directory '/home/openwrt-sdk-19.07.2-apm821xx-nand_gcc-7.5.0_musl.Linux-x86_64'
/home/openwrt-sdk-19.07.2-apm821xx-nand_gcc-7.5.0_musl.Linux-x86_64/include/toplevel.mk:218: recipe for target 'package/trojan/compile' failed
make: *** [package/trojan/compile] Error 2
同样更换了openwrt-sdk-19.07.2-ipq40xx-generic_gcc-7.5.0_musl_eabi.Linux-x86_64
编译还是失败。。求解答。谷歌云和DO都失败

**Comment by wonpn** [comment]
我也是同样的问题，
解决了吗？

**Comment by zealforbeing** [comment]
同样的问题
