### ISSUE TITLE
openwrt-sdk-19.07.2-ipq806x 编译失败

### ISSUE THREAD

**Issue by dmcdark** [trojan-gfw/openwrt-trojan#19]
系统Ubuntu 19.10

https://downloads.openwrt.org/releases/19.07.2/targets/ipq806x/generic/openwrt-sdk-19.07.2-ipq806x-generic_gcc-7.5.0_musl_eabi.Linux-x86_64.tar.xz
下载SDK、解压。

apt-get update
安装工具
apt-get install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc wget unzip python time

之前还装了：sudo apt-get install git-core build-essential libssl-dev libncurses5-dev unzip gawk
sudo apt-get install subversion mercurial
sudo apt-get install ccache

下载openwrt-trojan
git clone https://github.com/trojan-gfw/openwrt-trojan.git
mv openwrt-trojan/* ./

安装feeds
./scripts/feeds update -a
./scripts/feeds install -a

进入make menuconfig
make menuconfig

进入Global build settings
勾掉前三个星号，保存

进入network
星号勾选trojan，保存，退出

然后执行编译trojan
make package/trojan/compile -j 4 V=99

报错：

-- Configuring incomplete, errors occurred!
See also "/home/darkzack/openwrt-sdk-19.07.2-ipq806x-generic_gcc-7.5.0_musl_eabi.Linux-x86_64/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/trojan-1.14.1/CMakeFiles/CMakeOutput.log".
make[2]: *** [Makefile:93: /home/darkzack/openwrt-sdk-19.07.2-ipq806x-generic_gcc-7.5.0_musl_eabi.Linux-x86_64/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/trojan-1.14.1/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
make[2]: Leaving directory '/home/darkzack/openwrt-sdk-19.07.2-ipq806x-generic_gcc-7.5.0_musl_eabi.Linux-x86_64/package/trojan'
time: package/trojan/compile#0.54#0.29#3.66
make[1]: *** [package/Makefile:113: package/trojan/compile] Error 2
make[1]: Leaving directory '/home/darkzack/openwrt-sdk-19.07.2-ipq806x-generic_gcc-7.5.0_musl_eabi.Linux-x86_64'
make: *** [/home/darkzack/openwrt-sdk-19.07.2-ipq806x-generic_gcc-7.5.0_musl_eabi.Linux-x86_64/include/toplevel.mk:220: package/trojan/compile] Error 2

请问是我哪步错了或者少了什么步骤吗？谢谢

附上CMakeOutput.log
[CMakeOutput.log](https://github.com/trojan-gfw/openwrt-trojan/files/4345110/CMakeOutput.log)

**Comment by wazzx** [comment]
看到是同一个教程 问一下git那一步是在Sdk的pack中进行的吗？按照那个教程我这边的虚理机18.03是成功了的。

**Comment by dmcdark** [comment]
> 看到是同一个教程 问一下git那一步是在Sdk的pack中进行的吗？按照那个教程我这边的虚理机18.03是成功了的。

git clone那部吗？应该怎么做？

**Comment by wazzx** [comment]
> > 看到是同一个教程 问一下git那一步是在Sdk的pack中进行的吗？按照那个教程我这边的虚理机18.03是成功了的。
> 
> git xlone那部吗？应该怎么做？

系统回到18.03，然后看一下git clone 那一步是在pack中进行的吗！

**Comment by dmcdark** [comment]
> > > 看到是同一个教程 问一下git那一步是在Sdk的pack中进行的吗？按照那个教程我这边的虚理机18.03是成功了的。
> > 
> > 
> > git xlone那部吗？应该怎么做？
> 
> 系统回到18.03，然后看一下git clone 那一步是在pack中进行的吗！

呃。。。什么叫做在pack中进行的啊？算了，我不在openwrt上跑了，发现其实cpu也不够好
