### ISSUE TITLE
compile error openwrt chaos_calmer 15.05

### ISSUE THREAD

**Issue by clswang** [trojan-gfw/openwrt-trojan#2]
openwrt chaos_calmer 15.05 ,CMake upgraded to 3.7.2

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   THREADS_PTHREAD_ARG (advanced)
For details see /home/mac/openwrtcc/chaos_calmer/build_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/trojan-1.10.0/TryRunResults.cmake
-- Check if compiler accepts -pthread - no
-- Found Threads: TRUE
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   program_options
-- Found OpenSSL: /home/mac/openwrtcc/chaos_calmer/build_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/openssl1.1_staging_dir/usr/lib/libssl.a;/home/mac/openwrtcc/chaos_calmer/build_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/openssl1.1_staging_dir/usr/lib/libcrypto.a (found suitable version "1.1.1a", minimum required is "1.1.1")
-- Configuring incomplete, errors occurred!
See also "/home/mac/openwrtcc/chaos_calmer/build_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/trojan-1.10.0/CMakeFiles/CMakeOutput.log".
See also "/home/mac/openwrtcc/chaos_calmer/build_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/trojan-1.10.0/CMakeFiles/CMakeError.log".
Makefile:81: recipe for target '/home/mac/openwrtcc/chaos_calmer/build_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/trojan-1.10.0/.configured_yyyyyyyy' failed
make[2]: *** [/home/mac/openwrtcc/chaos_calmer/build_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/trojan-1.10.0/.configured_yyyyyyyy] Error 1
make[2]: Leaving directory '/home/mac/openwrtcc/chaos_calmer/package/openwrt-trojan/trojan'
package/Makefile:191: recipe for target 'package/openwrt-trojan/trojan/compile' failed
make[1]: *** [package/openwrt-trojan/trojan/compile] Error 2
make[1]: Leaving directory '/home/mac/openwrtcc/chaos_calmer'
/home/mac/openwrtcc/chaos_calmer/include/toplevel.mk:181: recipe for target 'package/openwrt-trojan/trojan/compile' failed
make: *** [package/openwrt-trojan/trojan/compile] Error 2

**Comment by wongsyrone** [comment]
Try latest version from https://downloads.openwrt.org/releases/

**Comment by wongsyrone** [comment]
> CMake upgraded to 3.7.2

BTW, openwrt buildroot doesn't use your distro's CMake, it uses the embedded one.

**Comment by clswang** [comment]
Thanks, compile success on 18.06.1.
