### ISSUE TITLE
Unify default config file path?

### ISSUE THREAD

**Issue by zachcheung** [trojan-gfw/openwrt-trojan#20]
default config path of trojan-gfw is `/etc/trojan/config.json`, while `/etc/trojan.json` in `trojan.init` of openwrt-trojan, any specific reason for it? why not keep consistent to use `/etc/trojan/config.json`?

**Comment by wongsyrone** [comment]
If we have multiple files, we will put them in a specific folder. In this case, we have only one file.

**Comment by zachcheung** [comment]
got it, it make sense.

**Comment by zachcheung** [comment]
A user case suddenly came to me, have multiple trojan-gfw configs because of different servers, use symlink to `config.json`, in such case, it's better to has dedicated dir to mange configs.

**Comment by zachcheung** [comment]
have changed back default config path to keep consistent with upstream and minor update init script in [my fork](https://github.com/ZachCheung/openwrt-trojan), if anyone has interest, check it please.
