### ISSUE TITLE
openwrt 19.07.2 有openssl 1.1.1e 版

### ISSUE THREAD

**Issue by kousyougi** [trojan-gfw/openwrt-trojan#21]
openwrt 官網的 19.07.2 有openssl 1.1.1e可以直接裝。
請問我照這個compile的時候要怎麼把openssl 1.1.1d排除掉，想直接用openwrt內建的openssl。
另外
目前這個makefile可以直接用來compile新版1.15.1版的trojan嗎？
謝謝

**Comment by wongsyrone** [comment]
Updated.

**Comment by wazzx** [comment]
> Updated.

大佬我上回改了一下makefile直接编译出来了1.15.1不过不知道怎么样还没有配置

**Comment by kousyougi** [comment]
剛剛在Ubuntu上compile完，x86-64的版本。可以正常跑。
謝謝

**Comment by txdywy** [comment]
编译报patch错误。改回之前openssl编译成功

kousyougi <notifications@github.com> 于 2020年3月31日周二 下午1:32写道：

**Comment by txdywy** [comment]
折腾一圈不知为何又成功了
