### ISSUE TITLE
How can I use openssl from openwrt?

### ISSUE THREAD

**Issue by kousyougi** [trojan-gfw/openwrt-trojan#29]
How can I use openssl from openwrt?
just delete <openssl1.1> folder?

If built-in openssl version is 1.1.1g, would I have cutting-edge features, e.g. TLS 1.3 while using openssl from openwrt?

and need 1.16.0 update. thanks

**Comment by wongsyrone** [comment]
> How can I use openssl from openwrt?
> just delete <openssl1.1> folder?

You should modify Makefiles accordingly.

> If built-in openssl version is 1.1.1g, would I have cutting-edge features, e.g. TLS 1.3 while using openssl from openwrt?

Depends on the OpenSSL version in your repository.

> and need 1.16.0 update. thanks

I Will update in several days.

**Comment by wongsyrone** [comment]
Done.
