### ISSUE TITLE
Hi I have compiled the ipk packages and Upload to the tmp directory to install  But I got the installation errors

### ISSUE THREAD

**Issue by brookwko** [trojan-gfw/openwrt-trojan#7]
root@OpenWrt:/tmp# opkg install boost_*.ipk boost-system_*.ipk boost-program_options_*.ipk boost-date_time_*.ipk trojan_*.ipk

Installing boost (1.68.0-6) to root...
Downloading http://mirror.0x.sg/openwrt/releases/18.06.4/packages/arm_cortex-a9/packages/boost_1.68.0-6_arm_cortex-a9.ipk
Installing boost-system (1.68.0-6) to root...
Downloading http://mirror.0x.sg/openwrt/releases/18.06.4/packages/arm_cortex-a9/packages/boost-system_1.68.0-6_arm_cortex-a9.ipk
Installing boost-program_options (1.68.0-6) to root...
Downloading http://mirror.0x.sg/openwrt/releases/18.06.4/packages/arm_cortex-a9/packages/boost-program_options_1.68.0-6_arm_cortex-a9.ipk
Installing boost-date_time (1.68.0-6) to root...
Downloading http://mirror.0x.sg/openwrt/releases/18.06.4/packages/arm_cortex-a9/packages/boost-date_time_1.68.0-6_arm_cortex-a9.ipk
Unknown package 'trojan'.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for boost:
 * 	libstdcpp
 * 	librt
 * opkg_install_cmd: Cannot install package boost.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for boost-system:
 * 	libstdcpp
 * 	librt
 * opkg_install_cmd: Cannot install package boost-system.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for boost-program_options:
 * 	libstdcpp
 * 	librt
 * opkg_install_cmd: Cannot install package boost-program_options.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for boost-date_time:
 * 	libstdcpp
 * 	librt
 * opkg_install_cmd: Cannot install package boost-date_time.
 * pkg_hash_fetch_best_installation_candidate: Packages for trojan found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package trojan.

**Comment by wongsyrone** [comment]
`opkg install libstdcpp librt`

**Comment by brookwko** [comment]
The problem seems to remain

root@OpenWrt:~# opkg install libstdcpp librt
Unknown package 'libstdcpp'.
Unknown package 'librt'.
Collected errors:
 * opkg_install_cmd: Cannot install package libstdcpp.
 * opkg_install_cmd: Cannot install package librt.


i using the version of openwrt is 18.06.4

**Comment by wongsyrone** [comment]
Make sure you execute `opkg update` first to get the latest package index. Check opkg configurations as well.

```
root@OpenWrt:~# cat /etc/opkg.conf 
dest root /
dest ram /tmp
lists_dir ext /var/opkg-lists
option overlay_root /overlay
option check_signature
root@OpenWrt:~# cat /etc/opkg/
customfeeds.conf  distfeeds.conf    keys/
root@OpenWrt:~# cat /etc/opkg/distfeeds.conf 
src/gz openwrt_core http://downloads.openwrt.org/snapshots/targets/x86/64/packages
src/gz openwrt_base http://downloads.openwrt.org/snapshots/packages/x86_64/base
src/gz openwrt_luci http://downloads.openwrt.org/snapshots/packages/x86_64/luci
src/gz openwrt_management http://downloads.openwrt.org/snapshots/packages/x86_64/management
src/gz openwrt_packages http://downloads.openwrt.org/snapshots/packages/x86_64/packages
src/gz openwrt_routing http://downloads.openwrt.org/snapshots/packages/x86_64/routing
src/gz openwrt_targets http://downloads.openwrt.org/snapshots/packages/x86_64/targets
src/gz openwrt_telephony http://downloads.openwrt.org/snapshots/packages/x86_64/telephony
root@OpenWrt:~# cat /etc/opkg/customfeeds.conf 
# add your custom package feeds here
#
# src/gz example_feed_name http://www.example.com/path/to/files
root@OpenWrt:~#
```

**Comment by brookwko** [comment]
Changed my  'distfeeds.conf' file configuration after it worked  but another error  occurred

root@OpenWrt:/tmp# opkg install boost_*.ipk boost-system_*.ipk boost-program_options_*.ipk boost-date_time_*.ipk trojan_*.ipk
Installing boost (1.68.0-6) to root...
Downloading http://mirror.0x.sg/openwrt/releases/18.06.4/packages/arm_cortex-a9/packages/boost_1.68.0-6_arm_cortex-a9.ipk
Installing libstdcpp (7.3.0-1) to root...
Downloading http://mirror.0x.sg/openwrt/releases/18.06.4/targets/bcm53xx/generic/packages//libstdcpp_7.3.0-1_arm_cortex-a9.ipk
Installing librt (1.1.19-1) to root...
Downloading http://mirror.0x.sg/openwrt/releases/18.06.4/targets/bcm53xx/generic/packages//librt_1.1.19-1_arm_cortex-a9.ipk
Installing boost-system (1.68.0-6) to root...
Downloading http://mirror.0x.sg/openwrt/releases/18.06.4/packages/arm_cortex-a9/packages/boost-system_1.68.0-6_arm_cortex-a9.ipk
Installing boost-program_options (1.68.0-6) to root...
Downloading http://mirror.0x.sg/openwrt/releases/18.06.4/packages/arm_cortex-a9/packages/boost-program_options_1.68.0-6_arm_cortex-a9.ipk
Installing boost-date_time (1.68.0-6) to root...
Downloading http://mirror.0x.sg/openwrt/releases/18.06.4/packages/arm_cortex-a9/packages/boost-date_time_1.68.0-6_arm_cortex-a9.ipk
Unknown package 'trojan'.
Configuring libstdcpp.
Configuring librt.
Configuring boost-date_time.
Configuring boost.
Configuring boost-program_options.
Configuring boost-system.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for trojan found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package trojan.

**Comment by wongsyrone** [comment]
> but incompatible with the architectures configured

Do NOT copy & paste what I posted blindly, use the appropriate URL for your arch.

**Comment by brookwko** [comment]
I didn't copy your configuration, just check my configuration and change, I don't know what is arch,Whether it is aarch64 cortexa53 but i use arm_cortex-a9

**Comment by brookwko** [comment]
I recompile with my routing version of sdk, it is installed,the author is not friendly,"arch" means architecture, this is quite a scribble
