### ISSUE TITLE
How to use it in Openwrt or LEDE?

### ISSUE THREAD

**Issue by f3404923** [trojan-gfw/openwrt-trojan#9]
I had compiled the trojan to LEDE, but I do not know how to use it. Can you tell me?

**Comment by babylife** [comment]
same question。 seems need to build via openwrt source code?  how about Merlin?

**Comment by f3404923** [comment]
I got some information about this in youtube. The trojan of lede can  config in "network menu". but if you want to use it, you have to config  it by console, it is difficult for me.  @babylife

**Comment by psyvirgin** [comment]
The same problem.  There is no trojan config UI

**Comment by henrykey** [comment]
I’m thinking about this way. Trojan client could be installed in a normal Linux with socks as regular inbound and setup a v2ray on an openwrt router with an outbound of socks to forward traffic to the Trojan client and routing capability of v2ray could be used for transparent proxy. Of course u got to have a VPS Trojan server ready.

**Comment by cokebar** [comment]
Now you can only use it by console or shell script. There's no existing luci-app.
For shadowsocks, we have luci-app-shadowsocks: https://github.com/shadowsocks/luci-app-shadowsocks
For trojan we can take luci-app-shadowsocks as an example and make a similar one.

**Comment by zxdong262** [comment]
I can find that trojan is in network menu, press `Y` to turn it on. After `make`, there will be an trojan ipk file in `staging_dir/packages`, and I tried `opkg install trojan_1.14.1-3_arm_cortex-a9.ipk`, got error: `pkg_hash_fetch_best_installation_candidate: Packages for trojan found, but incompatible with the architectures configured`

**Comment by txdywy** [comment]
没选对架构编译

ZHAO Xudong <notifications@github.com> 于 2020年2月26日周三 下午11:38写道：

**Comment by zxdong262** [comment]
我的asus RT87U, 我看都选对了Target: bcm53xx architecture: arm_cortex-a9, 还有个专门的87u profile, 请教还有什么地方要设置呢 @txdywy
